# Generated by Django 4.0.3 on 2022-03-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='view',
        ),
    ]
