# Generated by Django 4.0.3 on 2022-03-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
