# Generated by Django 4.0.3 on 2022-03-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='views',
        ),
    ]
